[features]
seeds = false
skip-lint = false
[programs.localnet]
programs = "GKUC7b5F57TM8J4w2wms9p6qxsSN96QJnzJCBVaqVTEw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/rookasrudzianskas/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
